--- #YAML:1.0
name:               B-Debugger
version:            0.10
abstract:           optree debugger
author:
    - Reini Urban <rurban@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B:            1.09
    B::Concise:   0.66
    B::Flags:     0.02
    B::Utils:     0.05
    Devel::Hook:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
