--- #YAML:1.0
name:                B-Debugger
version:             0.01_01
abstract:            optree debugger
license:             ~
author:              
    - Reini Urban <rurban@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    B:                             1.17
    B::Concise:                    0.74
    B::Flags:                      0.01
    B::Utils:                      0.05
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
